version: '3.7'

services:
  ignite:
    image: apacheignite/ignite:latest
    environment:
      CONFIG_URI: https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-cache.xml
      OPTION_LIBS: ignite-log4j
    ports:
      - "47500-47509:47500-47509"