version: '3.7'

services:
  ignite:
    image: apacheignite/ignite:latest
    environment:
      CONFIG_URI: https://raw.githubusercontent.com/sausageRoll/ignite-test/master/src/main/resources/ignite/server-config.xml
      OPTION_LIBS: ignite-log4j
    ports:
      - "47500-47509:47500-47509"
      - "10800:10800"
      - "11211:11211"
      - "47100:47100"
      - "47400:47400"
      - "8080:8080"
      - "49128:49128"
      - "31100-31200:31100-31200"
      - "48100-48200:48100-48200"
